name: E2E on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./e2e
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "https://www.saucedemo.com"
